/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package acrobot_types;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcmt_motor_state implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double current;
    public double position;
    public double position2;
    public byte fault;
 
    public lcmt_motor_state()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x897e54ba4eb6e80fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(acrobot_types.lcmt_motor_state.class))
            return 0L;
 
        classes.add(acrobot_types.lcmt_motor_state.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.current); 
 
        outs.writeDouble(this.position); 
 
        outs.writeDouble(this.position2); 
 
        outs.writeByte(this.fault); 
 
    }
 
    public lcmt_motor_state(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcmt_motor_state(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static acrobot_types.lcmt_motor_state _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        acrobot_types.lcmt_motor_state o = new acrobot_types.lcmt_motor_state();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.current = ins.readDouble();
 
        this.position = ins.readDouble();
 
        this.position2 = ins.readDouble();
 
        this.fault = ins.readByte();
 
    }
 
    public acrobot_types.lcmt_motor_state copy()
    {
        acrobot_types.lcmt_motor_state outobj = new acrobot_types.lcmt_motor_state();
        outobj.timestamp = this.timestamp;
 
        outobj.current = this.current;
 
        outobj.position = this.position;
 
        outobj.position2 = this.position2;
 
        outobj.fault = this.fault;
 
        return outobj;
    }
 
}

