/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package acrobot_types;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcmt_motor_command implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double command;
    public byte command_type;
    public byte fault;
 
    public lcmt_motor_command()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x936ff3b11565e0c5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(acrobot_types.lcmt_motor_command.class))
            return 0L;
 
        classes.add(acrobot_types.lcmt_motor_command.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.command); 
 
        outs.writeByte(this.command_type); 
 
        outs.writeByte(this.fault); 
 
    }
 
    public lcmt_motor_command(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcmt_motor_command(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static acrobot_types.lcmt_motor_command _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        acrobot_types.lcmt_motor_command o = new acrobot_types.lcmt_motor_command();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.command = ins.readDouble();
 
        this.command_type = ins.readByte();
 
        this.fault = ins.readByte();
 
    }
 
    public acrobot_types.lcmt_motor_command copy()
    {
        acrobot_types.lcmt_motor_command outobj = new acrobot_types.lcmt_motor_command();
        outobj.timestamp = this.timestamp;
 
        outobj.command = this.command;
 
        outobj.command_type = this.command_type;
 
        outobj.fault = this.fault;
 
        return outobj;
    }
 
}

