"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class lcmt_acrobot_y(object):
    __slots__ = ["timestamp", "theta1", "theta2", "tau"]

    def __init__(self):
        self.timestamp = 0
        self.theta1 = 0.0
        self.theta2 = 0.0
        self.tau = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(lcmt_acrobot_y._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddd", self.timestamp, self.theta1, self.theta2, self.tau))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != lcmt_acrobot_y._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_acrobot_y._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_acrobot_y()
        self.timestamp, self.theta1, self.theta2, self.tau = struct.unpack(">qddd", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_acrobot_y in parents: return 0
        tmphash = (0x1b1a2a81e14c5a07) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_acrobot_y._packed_fingerprint is None:
            lcmt_acrobot_y._packed_fingerprint = struct.pack(">Q", lcmt_acrobot_y._get_hash_recursive([]))
        return lcmt_acrobot_y._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

