/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package acrobot_types;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcmt_acrobot_x implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double theta1;
    public double theta1Dot;
    public double theta2;
    public double theta2Dot;
 
    public lcmt_acrobot_x()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x208cbb64fedaeaecL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(acrobot_types.lcmt_acrobot_x.class))
            return 0L;
 
        classes.add(acrobot_types.lcmt_acrobot_x.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.theta1); 
 
        outs.writeDouble(this.theta1Dot); 
 
        outs.writeDouble(this.theta2); 
 
        outs.writeDouble(this.theta2Dot); 
 
    }
 
    public lcmt_acrobot_x(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcmt_acrobot_x(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static acrobot_types.lcmt_acrobot_x _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        acrobot_types.lcmt_acrobot_x o = new acrobot_types.lcmt_acrobot_x();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.theta1 = ins.readDouble();
 
        this.theta1Dot = ins.readDouble();
 
        this.theta2 = ins.readDouble();
 
        this.theta2Dot = ins.readDouble();
 
    }
 
    public acrobot_types.lcmt_acrobot_x copy()
    {
        acrobot_types.lcmt_acrobot_x outobj = new acrobot_types.lcmt_acrobot_x();
        outobj.timestamp = this.timestamp;
 
        outobj.theta1 = this.theta1;
 
        outobj.theta1Dot = this.theta1Dot;
 
        outobj.theta2 = this.theta2;
 
        outobj.theta2Dot = this.theta2Dot;
 
        return outobj;
    }
 
}

