"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class lcmt_copleyState(object):
    __slots__ = ["timestamp", "force", "current", "position", "velocity", "fault"]

    def __init__(self):
        self.timestamp = 0
        self.force = 0
        self.current = 0
        self.position = 0.0
        self.velocity = 0.0
        self.fault = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(lcmt_copleyState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhhddb", self.timestamp, self.force, self.current, self.position, self.velocity, self.fault))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != lcmt_copleyState._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_copleyState._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_copleyState()
        self.timestamp, self.force, self.current, self.position, self.velocity, self.fault = struct.unpack(">qhhddb", buf.read(29))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmt_copleyState in parents: return 0
        tmphash = (0xa721a54bb8870f5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_copleyState._packed_fingerprint is None:
            lcmt_copleyState._packed_fingerprint = struct.pack(">Q", lcmt_copleyState._get_hash_recursive([]))
        return lcmt_copleyState._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

