/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package acrobot_types;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcmt_copleyState implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public short force;
    public short current;
    public double position;
    public double velocity;
    public byte fault;
 
    public lcmt_copleyState()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0a721a54bb8870f5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(acrobot_types.lcmt_copleyState.class))
            return 0L;
 
        classes.add(acrobot_types.lcmt_copleyState.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeShort(this.force); 
 
        outs.writeShort(this.current); 
 
        outs.writeDouble(this.position); 
 
        outs.writeDouble(this.velocity); 
 
        outs.writeByte(this.fault); 
 
    }
 
    public lcmt_copleyState(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcmt_copleyState(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static acrobot_types.lcmt_copleyState _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        acrobot_types.lcmt_copleyState o = new acrobot_types.lcmt_copleyState();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.force = ins.readShort();
 
        this.current = ins.readShort();
 
        this.position = ins.readDouble();
 
        this.velocity = ins.readDouble();
 
        this.fault = ins.readByte();
 
    }
 
    public acrobot_types.lcmt_copleyState copy()
    {
        acrobot_types.lcmt_copleyState outobj = new acrobot_types.lcmt_copleyState();
        outobj.timestamp = this.timestamp;
 
        outobj.force = this.force;
 
        outobj.current = this.current;
 
        outobj.position = this.position;
 
        outobj.velocity = this.velocity;
 
        outobj.fault = this.fault;
 
        return outobj;
    }
 
}

