// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lcmt_pendulum_y_h
#define _lcmt_pendulum_y_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmt_pendulum_y lcmt_pendulum_y;
struct _lcmt_pendulum_y
{
    int64_t    timestamp;
    double     theta;
    double     tau;
};

/**
 * Create a deep copy of a lcmt_pendulum_y.
 * When no longer needed, destroy it with lcmt_pendulum_y_destroy()
 */
lcmt_pendulum_y* lcmt_pendulum_y_copy(const lcmt_pendulum_y* to_copy);

/**
 * Destroy an instance of lcmt_pendulum_y created by lcmt_pendulum_y_copy()
 */
void lcmt_pendulum_y_destroy(lcmt_pendulum_y* to_destroy);

/**
 * Identifies a single subscription.  This is an opaque data type.
 */
typedef struct _lcmt_pendulum_y_subscription_t lcmt_pendulum_y_subscription_t;

/**
 * Prototype for a callback function invoked when a message of type
 * lcmt_pendulum_y is received.
 */
typedef void(*lcmt_pendulum_y_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const lcmt_pendulum_y *msg, void *userdata);

/**
 * Publish a message of type lcmt_pendulum_y using LCM.
 *
 * @param lcm The LCM instance to publish with.
 * @param channel The channel to publish on.
 * @param msg The message to publish.
 * @return 0 on success, <0 on error.  Success means LCM has transferred
 * responsibility of the message data to the OS.
 */
int lcmt_pendulum_y_publish(lcm_t *lcm, const char *channel, const lcmt_pendulum_y *msg);

/**
 * Subscribe to messages of type lcmt_pendulum_y using LCM.
 *
 * @param lcm The LCM instance to subscribe with.
 * @param channel The channel to subscribe to.
 * @param handler The callback function invoked by LCM when a message is received.
 *                This function is invoked by LCM during calls to lcm_handle() and
 *                lcm_handle_timeout().
 * @param userdata An opaque pointer passed to @p handler when it is invoked.
 * @return 0 on success, <0 if an error occured
 */
lcmt_pendulum_y_subscription_t* lcmt_pendulum_y_subscribe(lcm_t *lcm, const char *channel, lcmt_pendulum_y_handler_t handler, void *userdata);

/**
 * Removes and destroys a subscription created by lcmt_pendulum_y_subscribe()
 */
int lcmt_pendulum_y_unsubscribe(lcm_t *lcm, lcmt_pendulum_y_subscription_t* hid);

/**
 * Sets the queue capacity for a subscription.
 * Some LCM providers (e.g., the default multicast provider) are implemented
 * using a background receive thread that constantly revceives messages from
 * the network.  As these messages are received, they are buffered on
 * per-subscription queues until dispatched by lcm_handle().  This function
 * how many messages are queued before dropping messages.
 *
 * @param subs the subscription to modify.
 * @param num_messages The maximum number of messages to queue
 *  on the subscription.
 * @return 0 on success, <0 if an error occured
 */
int lcmt_pendulum_y_subscription_set_queue_capacity(lcmt_pendulum_y_subscription_t* subs,
                              int num_messages);

/**
 * Encode a message of type lcmt_pendulum_y into binary form.
 *
 * @param buf The output buffer.
 * @param offset Encoding starts at this byte offset into @p buf.
 * @param maxlen Maximum number of bytes to write.  This should generally
 *               be equal to lcmt_pendulum_y_encoded_size().
 * @param msg The message to encode.
 * @return The number of bytes encoded, or <0 if an error occured.
 */
int lcmt_pendulum_y_encode(void *buf, int offset, int maxlen, const lcmt_pendulum_y *p);

/**
 * Decode a message of type lcmt_pendulum_y from binary form.
 * When decoding messages containing strings or variable-length arrays, this
 * function may allocate memory.  When finished with the decoded message,
 * release allocated resources with lcmt_pendulum_y_decode_cleanup().
 *
 * @param buf The buffer containing the encoded message
 * @param offset The byte offset into @p buf where the encoded message starts.
 * @param maxlen The maximum number of bytes to read while decoding.
 * @param msg Output parameter where the decoded message is stored
 * @return The number of bytes decoded, or <0 if an error occured.
 */
int lcmt_pendulum_y_decode(const void *buf, int offset, int maxlen, lcmt_pendulum_y *msg);

/**
 * Release resources allocated by lcmt_pendulum_y_decode()
 * @return 0
 */
int lcmt_pendulum_y_decode_cleanup(lcmt_pendulum_y *p);

/**
 * Check how many bytes are required to encode a message of type lcmt_pendulum_y
 */
int lcmt_pendulum_y_encoded_size(const lcmt_pendulum_y *p);

// LCM support functions. Users should not call these
int64_t __lcmt_pendulum_y_get_hash(void);
uint64_t __lcmt_pendulum_y_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmt_pendulum_y_encode_array(void *buf, int offset, int maxlen, const lcmt_pendulum_y *p, int elements);
int     __lcmt_pendulum_y_decode_array(const void *buf, int offset, int maxlen, lcmt_pendulum_y *p, int elements);
int     __lcmt_pendulum_y_decode_array_cleanup(lcmt_pendulum_y *p, int elements);
int     __lcmt_pendulum_y_encoded_array_size(const lcmt_pendulum_y *p, int elements);
int     __lcmt_pendulum_y_clone_array(const lcmt_pendulum_y *p, lcmt_pendulum_y *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
